Release 159
1. Bump the XanMod Edge variant to 6.8.1.
2. Replace EXCLUDEBORE to BORE env. Going forward, BORE=1 selects BORE and PREEMPT preemption in the RT spec file. Default is PREEMPT_RT (no BORE).
3. Add patch for sched/fair to not force SMT balancing when CPU has spare capacity.
4. Add patch for HZ_600, HZ_750, and HZ_800. Default to 800 Hz for the Edige, Main, and LTS variants, in the xm-build script.
5. Update README.
6. Hz Testing: https://gist.github.com/marioroy/f383f1e9f18498a251beb5c0a9f33dcf
7. Latency testing: https://gist.github.com/marioroy/5b36c9b650cb2af42e702922a8466d69

diff --git a/xm-build b/xm-build
--- a/xm-build
+++ b/xm-build
@@ -18,7 +18,7 @@
 # -----------------------------------------------------------------------
 
 function xm_build {
-    variant="$1"
+    local variant="$1"
     echo "Building linux-${variant}."
 
     if [[ ! -d "SOURCES" ]]; then
@@ -26,14 +26,44 @@ function xm_build {
         exit 2
     fi
 
+    if [[ -n "$BORE" ]]; then
+        case "$BORE" in
+            0|1) # pass
+               ;;
+            *) echo "BORE=$BORE is invalid; try again."
+               exit 1
+        esac
+    fi
+
+    if [[ -n "$HZ" ]]; then
+        case "$HZ" in
+            1000|800|750|600|500|300|250|100) # pass
+               ;;
+            *) echo "HZ=$HZ is invalid; try again."
+               exit 1
+        esac
+    elif [[ "$variant" == "xmrt-preempt" ]]; then
+        HZ=1000
+    fi
+
+    if [[ -n "$LOCALMODCONFIG" ]]; then
+        case "$LOCALMODCONFIG" in
+            0|1) # pass
+               ;;
+            *) echo "LOCALMODCONFIG=$LOCALMODCONFIG is invalid; try again."
+               exit 1
+        esac
+    fi
+
     cp -a "../patches"/* "SOURCES"/
 
-    # The _excludebore definition is ignored for edge, main, and lts.
+    # The _bore definition is ignored for edge, main, and lts variants.
 
     ( rpmbuild -bb --clean "SPECS/linux-${variant}.spec" \
           --define "abi_package %{nil}" \
           --define "_buildhost $(hostname)" \
-          --define "_excludebore ${EXCLUDEBORE:-0}" \
+          --define "_bore ${BORE:-0}" \
+          --define "_hzval ${HZ:-800}" \
           --define "_localmodconfig ${LOCALMODCONFIG:-0}" \
           --define "_topdir ${PWD}" \
           --define "_unpackaged_files_terminate_build 0" \
@@ -45,7 +75,6 @@ function xm_build {
     ) 2>&1 | grep -Ev '^((chmod|find):.* No such file or directory|warning: Empty %files)'
 
     rm -fr BUILD BUILDROOT SRPMS
-    sync
 }
 
 case "$1" in
